# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a6e45896d3d2ee9e6b60124a692ca787902b01ad7bba6cdaf630591ef29d649a402896317982f18dbb1795368b5ff6bfaf0f2feeb22e8684e3c2d92fbf9a975

test:
  secret_key_base: 6b5f9cb595db2c081ad35092403d7a4af97da338b2668af7b42244b5b99abfa73deba8817408f6c3c6b390ddcd2babbdc2506339847403f18974570df9f49527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
